services:

  # -> Services -> Application AntiFraud.System
  antifraud-api:
    build:
      context: ../.
      dockerfile: src/Antifraud.System.Api/Dockerfile
    #image: ${DOCKER_REGISTRY-}antifraudapi
    image: antifraudapi
    hostname: api
    ports:
      - "5000:80"
    networks:
      - antifraud-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api
      - VIRTUAL_PORT=80
      - ConnectionStrings__DefaultConnection=Host=postgresql;Port=5432;Database=AntiFraudDb_Dev;Username=postgres;Password=AntiFraud@123
      - ConnectionStrings__Otlp=http://otel-collector:4317
      - Serilog__MinimumLevel__Default=Warning
      - Serilog__MinimumLevel__Override__Muralha=Information
      - Serilog__Using__0=Serilog.Sinks.Async
      - Serilog__Using__1=Serilog.Sinks.Console
      - Serilog__WriteTo__0__Name=Async
      - Serilog__WriteTo__0__Args__configure__0__Name=Console
      - Serilog__WriteTo__0__Args__configure__0__Args__theme=Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console
      - Serilog__WriteTo__0__Args__configure__0__Args__outputTemplate=[{Timestamp:HH:mm:ss.fff} {Level:u3}] [{MachineName}] {Message:lj}{NewLine}{Exception}
    depends_on:
      - postgres
      - rabbitmq
   
  # -> Services -> Databases (Serviços de banco de dados)
  postgres:
    restart: no
    extends:
      file: docker-compose-postgres.yaml
      service: postgres

  # -> Services -> Messaging (Mensageria entre serviços)
  rabbitmq:
    restart: no
    extends:
      file: docker-compose-rabbitmq.yaml
      service: rabbitmq
 
  # -> Observability (Monitoramento e Logs)
  # Serviço do coletor OpenTelemetry
  otel-collector:
    restart: no
    extends:
      file: docker-compose-otel.yaml
      service: otel-collector
      
  # Serviço do Prometheus
  prometheus:
    restart: no
    extends:
      file: docker-compose-prometheus.yaml
      service: prometheus

  # Serviço do Aspire Dashboard
  aspire-dashboard:
    restart: no
    extends:
      file: docker-compose-aspire-dashboard.yaml
      service: aspire-dashboard
    depends_on:
      - otel-collector

networks:
  antifraud-network:  
    driver: bridge 

# volumes => \\wsl.localhost\docker-desktop-data\data\docker\volumes
volumes:

  # -> Databases (Volumes de dados de banco de dados)
  postgres-data:      # Dados do Postgres

  # -> Messaging (Mensageria)
  rabbitmq-data:      # Dados do RabbitMQ

  # -> Observability (Monitoramento e Logs)
  prometheus-data:
  prometheus-config: