services:

  prometheus:
    # https://prometheus.io
    # https://github.com/prometheus/prometheus
    image: prom/prometheus:v3.6.0
    hostname: prometheus
    container_name: prometheus-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - antifraud-network
    extra_hosts:
      - "host.docker.internal=host-gateway"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.retention.size=100GB
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/etc/prometheus
      - prometheus-config:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

networks:
  antifraud-network:
    driver: bridge

volumes:
  prometheus-data:
  prometheus-config: